config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users

  resources :home, only: :index do
    collection do
      get 'contacts'
    end
  end

  resources :deals do
    member do
      post :add_attachment
    end
  end

  resources :tasks
  resource :user_management, only: [:show] do
    post '/:user_id/make_admin', action: :make_admin, as: :make_admin
    delete '/:user_id/remove', action: :remove_user, as: :remove_user
  end

  namespace :api do
    namespace :v1 do
      resources :contacts, only: [:index, :show, :create, :update, :destroy]
      resources :deals, only: [:index, :create]
    end
  end
  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.not_found_error_class
    ActiveRecord::RecordNotFound
  end

  def self.record_invalid_error_class
    ActiveRecord::RecordInvalid
  end
end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :attachable

  has_attached_file :document
  validates_attachment :document, :content_type => { :content_type => %w(application/pdf application/msword application/vnd.openxmlformats-officedocument.wordprocessingml.document) }
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  scope :by_user, ->(user) { where(user: user) }
  scope :by_user_id, ->(user_id) { where(user_id: user_id) }
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :user
  has_many :attachments, as: :attachable
  scope :by_user, ->(user) { where(user: user) }
  scope :by_user_id, ->(user_id) { where(user_id: user_id) }

end

app/models/role.rb
class Role < ApplicationRecord
  ADMIN_ROLE_TYPE = 1
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  scope :by_user, ->(user) { where(user: user) }
  scope :by_user_id, ->(user_id) { where(user_id: user_id) }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :invitable
  has_many :user_roles
  has_many :roles, through: :user_roles

  def is_admin?
    roles.where(role_type: Role::ADMIN_ROLE_TYPE).count != 0
  end
end

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/controllers/api/v1/base_controller.rb
module Api
  module V1
    class BaseController < ActionController::Base
      # skip_before_action :verify_authenticity_token
      respond_to :json
      def current_user_entity
        UserRepository.new.find(current_user.id)
      end
    end
  end
end

app/controllers/api/v1/contacts_controller.rb
module Api::V1
  class ContactsController < BaseController
    def index
      user = current_user_entity
      query = Contacts::FindAllInUsersScope.new(user)
      render json: query.execute, each_serializer: ContactSerializer, root: 'contacts'
    end

    def show
      user = current_user_entity
      contact_id = params[:id]
      query = Contacts::FindByIdInUsersScope.new(user, contact_id)
      render json: query.execute, serializer: ContactSerializer
    end

    def create
      user = current_user_entity
      action = Contacts::Add.new(user, params)
      action.execute
      if action.errors.empty?
        render json: action.result, serializer: ContactSerializer
      else
        render json: action.errors, status: 422
      end
    end

    def update
      user = current_user_entity
      action = Contacts::Update.new(user, params[:id], params)
      action.execute
      if action.errors.empty?
        render json: :ok
      else
        render json: action.errors, status: 422
      end
    end

    def destroy
      user = current_user_entity
      action = Contacts::Remove.new(user, params[:id])
      action.execute
      render json: :ok
    end
  end
end

app/controllers/api/v1/deals_controller.rb
module Api::V1
  class DealsController < BaseController
    def index
      user = current_user
      query = Deals::FindAllInUsersScope.new(user)
      render json: query.execute, each_serializer: DealSerializer, root: 'deals'
    end

    def create
      user = current_user
      action = Deals::Add.new(user, params)
      action.execute
      if action.errors.empty?
        render json: action.result, serializer: DealSerializer
      else
        render json: action.errors, status: 422
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user_entity
    UserRepository.new.find(current_user.id)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  def index
    user = current_user_entity
    query = Deals::FindAllInUsersScope.new(user)
    render :index, locals: { deals: query.execute, possible_stages: possible_stages}
  end

  def show
    user = current_user_entity
    deal = Deals::FindByIdInUsersScope.new(user, params.fetch(:id)).execute
    attachments = Attachments::FindAllInAttachableScope.new('deal', deal.id).execute

    render :show, locals:  {deal: deal, attachments: attachments }
  end

  def create
    user = current_user_entity
    action = Deals::Add.new(user, params)
    action.execute
    redirect_to deals_path
  end

  def edit
    user = current_user_entity
    query = Deals::FindByIdInUsersScope.new(user, params.fetch(:id))
    render :edit, locals:  {deal: query.execute, possible_stages: possible_stages }
  end

  def update
    user = current_user_entity
    action = Deals::Update.new(user, params[:id], params)
    action.execute
    redirect_to deals_path
  end

  def destroy
    user = current_user_entity
    action = Deals::Remove.new(user, params[:id])
    action.execute
    redirect_to deals_path
  end

  def add_attachment
    action = Attachments::Add.new('deal', params[:id], params)
    action.execute
    redirect_to deal_path(params[:id])
  end
  private

  def possible_stages
    Deals::Stage::STAGES.map { |k,v| [v, k] }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contacts
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    user = current_user_entity
    query = Tasks::FindAllInUsersScope.new(user)
    render :index, locals: { tasks: query.execute }
  end

  def create
    user = current_user_entity
    action = Tasks::Add.new(user, params)
    action.execute
    redirect_to tasks_path
  end

  def destroy
    user = current_user_entity
    action = Tasks::Remove.new(user, params[:id])
    action.execute
    redirect_to tasks_path
  end

  def edit
    user = current_user_entity
    query = Tasks::FindByIdInUsersScope.new(user, params.fetch(:id))
    render :edit, locals: {task: query.execute }
  end

  def update
    user = current_user_entity
    action = Tasks::Update.new(user, params[:id], params)
    action.execute
    redirect_to tasks_path
  end
end

app/controllers/user_managements_controller.rb
class UserManagementsController < ApplicationController
  def show
    query = Users::FindAllWithoutCurrentUser.new(current_user_entity)
    render :show, locals: { users: query.execute }
  end

  def remove_user
    user_id = params[:user_id]
    action = Users::Remove.new(user_id)
    action.execute

    redirect_to user_management_path
  end

  def make_admin
    user_id = params[:user_id]
    action = Users::MakeAdmin.new(user_id)
    action.execute

    redirect_to user_management_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user_entity
    UserRepository.new.find(current_user.id)
  end
end

app/views/deals/_form_contents.haml
.form-group
  =label_tag :name, 'Name'
  =text_field_tag :name, nil, class: 'form-control'
.form-group
  =label_tag :summary, 'Summary'
  =text_area_tag :summary, nil, class: 'form-control'
.form-group
  =label_tag :stage, 'Stage'
  =select_tag :stage, options_for_select(possible_stages), class: 'form-control'
.form-group
  =label_tag :amount, 'Amount'
  =number_field_tag :amount, nil, class: 'form-control'
=submit_tag 'Create', class: 'btn btn-default'

app/views/deals/edit.html.haml
.container
  = form_tag deal_path(deal.id), method: :patch do
    .form-group
      =label_tag :name, 'Name'
      =text_field_tag :name, deal.name, class: 'form-control'
    .form-group
      =label_tag :summary, 'Summary'
      =text_area_tag :summary, deal.summary, class: 'form-control'
    .form-group
      =label_tag :stage, 'Stage'
      =select_tag :stage, options_for_select(possible_stages), class: 'form-control'
    .form-group
      =label_tag :amount, 'Amount'
      =number_field_tag :amount, deal.amount, class: 'form-control'
    =submit_tag 'Create', class: 'btn btn-default'

app/views/deals/index.html.haml
.container
  .row
    .col-md-8
      %ul.list-unstyled
        - deals.each do |deal|
          %div{:classname => "deal-entity"}>
            %dl.dl-horizontal
            %dt Name
            %dd= deal.name
            %dt Stage
            %dd= deal.stage_name
            %dt Summary
            %dd= deal.summary
            %dt Amount
            %dd= deal.amount
          =link_to 'Show', deal_path(deal.id), class: 'btn btn-info'
          =link_to 'Edit', edit_deal_path(deal.id), class: 'btn btn-primary'
          =link_to 'Delete', deal_path(deal.id), class: 'btn btn-danger', method: :delete
    .col-md-4.scollableForm
      = form_tag deals_path, method: :post do
        = render :partial => 'form_contents', locals: { possible_stages: possible_stages }

app/views/deals/show.html.haml
.container
  .row
    =link_to 'Edit', edit_deal_path(deal.id), class: 'btn btn-primary'
    =link_to 'Delete', deal_path(deal.id), class: 'btn btn-danger', method: :delete

    %h3 Details
    %div
      %dl.dl-horizontal
      %dt Name
      %dd= deal.name
      %dt Stage
      %dd= deal.stage_name
      %dt Summary
      %dd= deal.summary
      %dt Amount
      %dd= deal.amount
    .row
      %div
        %h3 Attachments
        - attachments.each do |attachment|
          %div
            %a{href: attachment.document_url}
              =attachment.document_file_name
      %div
        %h3 Add new Attachment
        = form_for Attachment.new, url: add_attachment_deal_url(deal.id), html: { multipart: true } do |f|
          .form-group
            =f.label :document, 'Attachment'
            =f.file_field :document
          = submit_tag 'Add', class: 'btn btn-default'

app/views/home/contacts.html.haml
.container
  =react_component 'Components.ContactsBox', source: api_v1_contacts_url, target: api_v1_contacts_url

app/views/home/deals.html.haml
.container
  =react_component 'Components.DealsBox', source: api_v1_deals_url, target: api_v1_deals_url

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DddCrm
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track' => 'reload'
  %body
    %nav.navbar.navbar-default
      .container
        .navbar-header
          %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          =link_to 'The best crm', root_path, class: 'navbar-brand'
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          -if current_user
            %ul.nav.navbar-nav
              %li
                =link_to 'Manage contacts', contacts_home_index_path
              %li
                =link_to 'Manage deals', deals_path
              %li
                =link_to 'Manage tasks', tasks_path
              - if current_user_entity.is_admin?
                %li
                  =link_to 'Manage users', user_management_path
          %ul.nav.navbar-nav.navbar-right
            - if current_user
              %li
                = link_to 'Sing out', destroy_user_session_path, method: :delete
            - else
              %li
                = link_to 'Sing in', new_user_session_path

    = yield

app/views/tasks/_form_contents.haml
.form-group
  =label_tag :name, 'Name'
  =text_field_tag :name, nil, class: 'form-control'
.form-group
  =label_tag :description, 'Description'
  =text_area_tag :description, nil, class: 'form-control'
.form-group
  =label_tag :due_date, 'Due date'
  =datetime_field_tag :due_date, DateTime.now.to_s, class: 'form-control'
=submit_tag 'Create', class: 'btn btn-default'
:javascript

app/views/tasks/edit.html.haml
= form_tag task_path(task.id), method: :patch do
  .form-group
    =label_tag :name, 'Name'
    =text_field_tag :name, task.name, class: 'form-control'
  .form-group
    =label_tag :description, 'Description'
    =text_area_tag :description, task.description, class: 'form-control'
  .form-group
    =label_tag :due_date, 'Due date'
    =datetime_field_tag :due_date, task.due_date, class: 'form-control'
  =submit_tag 'Create', class: 'btn btn-default'

app/views/tasks/index.html.haml
.container
  .row
    .col-md-8
      %ul.list-unstyled
        - tasks.each do |task|
          %div{:classname => "task-entity"}>
            %dl.dl-horizontal
            %dt Name
            %dd= task.name
            %dt Description
            %dd= task.description
            %dt Due Date
            %dd= task.due_date
          =link_to 'Edit', edit_task_path(task.id), class: 'btn btn-primary'
          =link_to 'Delete', task_path(task.id), class: 'btn btn-danger', method: :delete
    .col-md-4.scollableForm
      = form_tag tasks_path, method: :post do
        = render :partial => 'form_contents'

app/views/user_managements/show.html.haml
.container
  .row
    =link_to 'Invite users', new_user_invitation_path, class: 'btn btn-primary'
    %ul
      - users.each do |user|
        %div
          %dl.dl-horizontal
          %dt Id
          %dd= user.id
          %dt Email
          %dd= user.email
        -unless user.is_admin?
          =link_to 'Make admin', make_admin_user_management_path(user.id), class: 'btn btn-info', method: :post
        =link_to 'Remove user', remove_user_user_management_path(user.id), class: 'btn btn-danger', method: :delete